version: '3.9'

services:
  tradeclub-backend:
    container_name: tradeclub-backend
    build: .
    command: npm run start:dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - tradeclub-db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - nest-network

  tradeclub-db:
    container_name: tradeclub-db
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-tradeclubdb}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nest-network

volumes:
  pgdata:

networks:
  nest-network:
    driver: bridge
