# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: tradeclub-indexer
description: TradeClub FUNDex and MatchManager event indexer
ecosystem: evm
schema: schema.graphql
field_selection:
  transaction_fields:
    - "hash"
networks:
  - id: 11155111 # Sepolia
    start_block: 7213000 # Adjust to your deployment block
    contracts:
      - name: FUNDex
        address: "0x16b0c1DCF87EBB4e0A0Ba4514FF0782CCE7889Cb"
        handler: src/EventHandlers.ts
        events:
          - event: PositionOpened(uint256 indexed positionId, address indexed trader, uint256 indexed assetId, uint8 positionType, uint256 collateral, uint256 size, uint256 leverage, uint256 entryPrice, uint256 timestamp)
          - event: PositionClosed(uint256 indexed positionId, address indexed trader, uint256 indexed assetId, uint256 exitPrice, int256 pnl, uint256 timestamp)
          - event: PriceUpdated(uint256 indexed assetId, string symbol, uint256 oldPrice, uint256 newPrice, uint256 timestamp)
          - event: Deposited(address indexed user, uint256 amount, uint256 newBalance)
          - event: Withdrawn(address indexed user, uint256 amount, uint256 newBalance)
      - name: MatchManager
        address: "0xb6Ad28b9f026704736c07abf21Dcb460c257aa66"
        handler: src/EventHandlers.ts
        events:
          - event: MatchCreated(uint256 indexed matchId, address indexed creator, uint256 entryMargin, uint256 duration, uint256 maxMonachads, uint256 maxSupportersPerMonachad, address[] allowedDexes)
          - event: MonachadJoined(uint256 indexed matchId, address indexed monachad, uint256 marginAmount, uint256 entryFee)
          - event: SupporterJoined(uint256 indexed matchId, address indexed supporter, address indexed monachad, address smartAccount, uint256 entryFee, uint256 fundedAmount)
          - event: MatchStarted(uint256 indexed matchId, uint256 startTime)
          - event: MatchCompleted(uint256 indexed matchId, address indexed winner, uint256 prizeAmount)
          - event: PnLUpdated(uint256 indexed matchId, address indexed participant, int256 pnl)
          - event: MatchVaultBalanceRecorded(uint256 indexed matchId, address indexed monachad, address indexed matchVault, uint256 preBalance, uint256 postBalance, int256 delta, uint8 changeType, uint256 timestamp)
          - event: GaveChadAMatchVault(uint256 indexed matchId, address indexed monachad, address matchVaultAddress)
rollback_on_reorg: false
save_full_history: false
